x-airflow-common:
  &airflow-common
  build:
    context: ./airflow/
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_METADATA_CONN}
    - AIRFLOW__CORE__EXECUTION_API_SERVER_URL=http://airflow-api-server:8080/execution
    - AIRFLOW__API_AUTH__JWT_SECRET=${AIRFLOW__API_AUTH__JWT_SECRET}
    - AIRFLOW__API_AUTH__JWT_ISSUER=airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Jakarta
    - AIRFLOW__CORE__AUTH_MANAGER=airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    - GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}
    - GOOGLE_AUTH_CLIENT_SECRET=${GOOGLE_AUTH_CLIENT_SECRET}
    - BUCKET_NAME=${BUCKET_NAME}
    - GARAGE_ENDPOINT_URL=${AWS_ENDPOINT_URL}
    - GOOGLE_TRENDS_MAX_KEYWORD_RETRIES=${GOOGLE_TRENDS_MAX_KEYWORD_RETRIES}
    - GOOGLE_TRENDS_SLEEP_SECONDS=${GOOGLE_TRENDS_SLEEP_SECONDS}
    - DW_USER=${DW_USER}
    - DW_PASSWORD=${DW_PASSWORD}
    - DW_DB=${DW_DB}
  env_file:
    - ./garage/.env.garage
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/config/webserver_config.py:/opt/airflow/webserver_config.py:ro
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    metadata:
      condition: service_healthy
  networks:
    - internal
  develop:
    watch:
      - action: rebuild
        path: ./airflow/requirements.txt
      - action: rebuild
        path: ./airflow/Dockerfile

services:
  # ---------------------------------------------------------------------------------------------------

  # Airflow
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_METADATA_CONN}
      - _AIRFLOW_DB_MIGRATE=true
    restart: on-failure

  airflow-api-server:
    <<: *airflow-common
    container_name: airflow-api-server
    command: api-server
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always

  airflow-triggerer:
    <<: *airflow-common
    container_name: airflow-triggerer
    command: triggerer
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow-dag-processor
    command: dag-processor
    restart: always

  # ---------------------------------------------------------------------------------------------------

  # Data Lake
  garage-init:
    container_name: garage-init
    build:
      context: ./garage/init
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
      - GARAGE_ADMIN_API=${GARAGE_ADMIN_API:-http://garage:3903}
      - GARAGE_NODE_CAPACITY=${GARAGE_NODE_CAPACITY:-1000000000}
      - BUCKET_NAME=${BUCKET_NAME:-ipbd-kelompok-5}
    volumes:
      - ./garage:/mnt/garage
    networks:
      - internal
    entrypoint: ["/bin/sh", "/usr/local/bin/garage-init.sh"]
    depends_on:
      garage:
        condition: service_healthy

  garage:
    container_name: garage
    image: dxflrs/garage:v2.3.0
    restart: unless-stopped
    ports:
      - 3900:3900 # S3 API
      - 3903:3903 # Admin API
    environment:
      - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET}
      - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
      - ./garage/meta:/var/lib/garage/meta
      - ./garage/data:/var/lib/garage/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  garage-webui:
    image: khairul169/garage-webui:1.1.0
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
    environment:
      - API_BASE_URL=http://garage:3903
      - S3_ENDPOINT_URL=http://garage:3900
      - API_ADMIN_KEY=${GARAGE_ADMIN_TOKEN}
      - AUTH_USER_PASS=${GARAGE_WEBUI_USER}:${GARAGE_WEBUI_HASHED_PASSWORD}
    networks:
      - internal
    depends_on:
      garage-init:
        condition: service_completed_successfully

  # ---------------------------------------------------------------------------------------------------

  # Data Warehouse
  dw:
    image: postgres:17-alpine
    container_name: dw
    environment:
      - POSTGRES_USER=${DW_USER}
      - POSTGRES_PASSWORD=${DW_PASSWORD}
      - POSTGRES_DB=${DW_DB}
    volumes:
      - ./dw/data:/var/lib/postgresql/data
      - ./dw/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------------------------------

  # Dashboard & Visualization
  metabase:
    image: metabase/metabase:v0.60.1.4
    container_name: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_METADATA_DB}
      MB_DB_PORT: ${METADATA_PORT:-5432} 
      MB_DB_USER: ${METADATA_USER}
      MB_DB_PASS: ${METADATA_PASSWORD}
      MB_DB_HOST: ${METADATA_HOST}
    networks:
      - internal
    depends_on:
      metadata:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------------------------------

  # Metadata for Airflow & Metabase
  metadata:
    image: postgres:17-alpine
    container_name: metadata
    environment:
      - POSTGRES_USER=${METADATA_USER}
      - POSTGRES_PASSWORD=${METADATA_PASSWORD}
      - POSTGRES_DB=${AIRFLOW_METADATA_DB}
      - METABASE_METADATA_DB=${METABASE_METADATA_DB} # Dipakai di entrypoint
    volumes:
      - ./metadata/data:/var/lib/postgresql/data
      - ./metadata/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  internal:
    external: true
