x-airflow-common:
  &airflow-common
  build:
    context: ./airflow/
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_METADATA_CONN}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Jakarta
    - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    metadata:
      condition: service_healthy
  networks:
    - internal
  develop:
    watch:
      - action: rebuild
        path: ./airflow/requirements.txt
      - action: rebuild
        path: ./airflow/Dockerfile

services:
  # ---------------------------------------------------------------------------------------------------

  # Airflow
  airflow-init:
    <<: *airflow-common
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_METADATA_CONN}
      - _AIRFLOW_DB_MIGRATE=true
    restart: on-failure

  airflow-api-server:
    <<: *airflow-common
    command: api-server
    ports:
      - "127.0.0.1:8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  # ---------------------------------------------------------------------------------------------------

  # Data Warehouse
  dw:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DW_USER}
      - POSTGRES_PASSWORD=${DW_PASSWORD}
      - POSTGRES_DB=${DW_DB}
    volumes:
      - ./dw_data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------------------------------

  # Dashboard & VIsualization
  metabase:
    image: metabase/metabase:v0.60.1.4
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_METADATA_DB}
      MB_DB_PORT: ${METADATA_PORT:-5432} 
      MB_DB_USER: ${METADATA_USER}
      MB_DB_PASS: ${METADATA_PASSWORD}
      MB_DB_HOST: ${METADATA_HOST}
    networks:
      - internal
    depends_on:
      metadata:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------------------------------------------------------

  # Metadata for Airflow & Metabase
  metadata:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${METADATA_USER}
      - POSTGRES_PASSWORD=${METADATA_PASSWORD}
      - POSTGRES_DB=${AIRFLOW_METADATA_DB}
      - METABASE_METADATA_DB=${METABASE_METADATA_DB} # Dipakai di entrypoint
    volumes:
      - ./metadata/data:/var/lib/postgresql/data
      - ./metadata/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  internal:
    external: true
